---
- name: Copy private key "{{ ssh_private_key_dest_path | basename }}"
  copy:
    dest: "{{ ssh_private_key_dest_path }}"
    content: "{{ ssh_private_key_content }}"
    owner: "{{ ssh_user_owner }}"
    group: "{{ ssh_user_owner }}"
    mode: "600"


- name: Copy public key "{{ ssh_public_key_dest_path | basename }}"
  copy:
    dest: "{{ ssh_public_key_dest_path }}"
    content: "{{ ssh_public_key_content }}"
    owner: "{{ ssh_user_owner }}"
    group: "{{ ssh_user_owner }}"
    mode: "600"
  when: ssh_public_key_content is defined


- name: Create ssh config file
  file:
    path: "{{ ansible_ssh_config_dir }}"
    state: touch
    owner: "{{ ssh_user_owner }}"
    group: "{{ ssh_user_owner }}"
    mode: "-rw-r--r--"
  when: ssh_host_usewith is defined
  changed_when: false

- name: set key for precise hosts
  blockinfile:
    marker: "#ssh-git-{{ ssh_host_item.host }}-{mark}"
    path: "{{ ansible_ssh_config_dir }}"
    block: |
      Host {{ ssh_host_item.host }}
        UserKnownHostsFile=/dev/null
        StrictHostKeyChecking=no
        IdentityFile {{ ssh_private_key_dest_path }}
  with_items: "{{ ssh_host_usewith }}"
  loop_control:
    loop_var: ssh_host_item
  when: ssh_host_usewith is defined