---
- name: Copy id_rsa key
  copy:
    dest: "{{ ssh_private_key_dest_path }}"
    content: "{{ ssh_private_key_content }}"
    owner: "{{ ssh_user_owner }}"
    group: "{{ ssh_user_owner }}"
    mode: "600"


- name: Copy id_rsa.pub key
  copy:
    dest: "{{ ssh_public_key_dest_path }}"
    content: "{{ ssh_public_key_content }}"
    owner: "{{ ssh_user_owner }}"
    group: "{{ ssh_user_owner }}"
    mode: "600"
  when: ssh_public_key_content is defined


- name: Create ssh config directory
  file:
    path: "{{ ansible_ssh_config_dir }}"
    state: touch
    owner: "{{ ssh_user_owner }}"
    group: "{{ ssh_user_owner }}"
    mode: "0700"
  when: ssh_host_usewith is defined


- name: add key for precise hosts
  blockinfile:
    path: "{{ ansible_ssh_config_dir }}"
    block: |
      Host {{ item.host }}
        IdentityFile {{ ssh_private_key_dest_path }}
  with_items: "{{ ssh_host_usewith }}"
  when: ssh_host_usewith is defined