---
- name: Include task list in play
  include_tasks: addkey.yml
  when: 
    - ssh_private_key_dest_path is defined
    - keys is undefined

- name: Include task list in play
  include_tasks: addkey.yml
  loop: "{{ keys }}"
  vars:
    ssh_private_key_dest_path: "{{ item.ssh_private_key_dest_path }}"
    ssh_public_key_dest_path: "{{ item.ssh_public_key_dest_path }}"
    ssh_user_owner: "{{ item.ssh_user_owner }}"
    ansible_ssh_config_dir: "{{ item.ansible_ssh_config_dir }}"
    ssh_host_usewith: "{{ item.ssh_host_usewith }}"
  when: 
    - ssh_private_key_dest_path is undefined
    - keys is defined